import type { Doc } from "./_generated/dataModel";

type SeedItem = Omit<Doc<"items">, "_id" | "_creationTime">;
type SeedCustomer = Omit<Doc<"customers">, "_id" | "_creationTime">;
type SeedInvoice = Omit<Doc<"invoices">, "_id" | "_creationTime">;
type SeedPayment = Omit<Doc<"payments">, "_id" | "_creationTime">;
type SeedClient = Omit<Doc<"clients">, "_id" | "_creationTime">;

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 86_400_000).toISOString();
const daysFromNow = (days: number) => new Date(now + days * 86_400_000).toISOString();

export const seedItems: SeedItem[] = [
  {
    id: "i1",
    name: "LED Bulb 9W",
    brand: "Philips",
    category: "Bulb",
    unit: "pc",
    purchasePrice: 45,
    retailPrice: 75,
    wholesalePrice: 60,
    stock: 500,
    minStock: 50,
    warrantyMonths: 12,
    lastSoldAt: daysAgo(1),
    alternates: [],
  },
  {
    id: "i2",
    name: "LED Tube 20W",
    brand: "Syska",
    category: "Bulb",
    unit: "pc",
    purchasePrice: 120,
    retailPrice: 180,
    wholesalePrice: 150,
    stock: 200,
    minStock: 30,
    warrantyMonths: 24,
    lastSoldAt: daysAgo(2),
    alternates: [],
  },
  {
    id: "i3",
    name: "Ceiling Fan 1200mm",
    brand: "Havells",
    category: "Fan",
    unit: "pc",
    purchasePrice: 1400,
    retailPrice: 2200,
    wholesalePrice: 1800,
    stock: 25,
    minStock: 5,
    warrantyMonths: 24,
    lastSoldAt: daysAgo(6),
    alternates: [],
  },
  {
    id: "i4",
    name: "Exhaust Fan 300mm",
    brand: "Crompton",
    category: "Fan",
    unit: "pc",
    purchasePrice: 800,
    retailPrice: 1200,
    wholesalePrice: 950,
    stock: 40,
    minStock: 10,
    warrantyMonths: 12,
    lastSoldAt: daysAgo(12),
    alternates: [],
  },
  {
    id: "i5",
    name: "Copper Wire 1.5sqmm",
    brand: "Finolex",
    category: "Wire",
    unit: "mtr",
    purchasePrice: 18,
    retailPrice: 28,
    wholesalePrice: 22,
    stock: 5000,
    minStock: 500,
    warrantyMonths: 0,
    lastSoldAt: daysAgo(1),
    alternates: [],
  },
  {
    id: "i6",
    name: "Copper Wire 2.5sqmm",
    brand: "Finolex",
    category: "Wire",
    unit: "mtr",
    purchasePrice: 28,
    retailPrice: 42,
    wholesalePrice: 35,
    stock: 3000,
    minStock: 300,
    warrantyMonths: 0,
    lastSoldAt: daysAgo(4),
    alternates: [],
  },
  {
    id: "i7",
    name: "MCB 16A Single",
    brand: "Schneider",
    category: "MCB",
    unit: "pc",
    purchasePrice: 120,
    retailPrice: 180,
    wholesalePrice: 150,
    stock: 100,
    minStock: 20,
    warrantyMonths: 36,
    lastSoldAt: daysAgo(10),
    alternates: [],
  },
  {
    id: "i8",
    name: "Switch Socket 6A",
    brand: "Anchor",
    category: "Switch",
    unit: "pc",
    purchasePrice: 35,
    retailPrice: 55,
    wholesalePrice: 45,
    stock: 300,
    minStock: 50,
    warrantyMonths: 12,
    lastSoldAt: daysAgo(5),
    alternates: [],
  },
];

export const seedCustomers: SeedCustomer[] = [
  {
    id: "c1",
    name: "Ramesh Kumar",
    phone: "9876543210",
    isElectrician: true,
    creditLimit: 50000,
    totalCredit: 15000,
    totalPaid: 35000,
    behaviorScore: "Good",
  },
  {
    id: "c2",
    name: "Suresh Patel",
    phone: "9876543211",
    isElectrician: true,
    creditLimit: 75000,
    totalCredit: 25000,
    totalPaid: 50000,
    behaviorScore: "Good",
  },
  {
    id: "c3",
    name: "Gopal Electricals",
    phone: "9876543212",
    isElectrician: false,
    creditLimit: 100000,
    totalCredit: 0,
    totalPaid: 120000,
    behaviorScore: "Good",
  },
  {
    id: "c4",
    name: "Mohan Singh",
    phone: "9876543213",
    isElectrician: false,
    creditLimit: 30000,
    totalCredit: 12000,
    totalPaid: 18000,
    behaviorScore: "Late",
  },
];

export const seedClients: SeedClient[] = [
  {
    id: "cl1",
    customerId: "c1",
    name: "Agarwal House",
    phone: "9800000001",
    address: "Sector 15, house wiring",
    createdAt: daysAgo(30),
  },
  {
    id: "cl2",
    customerId: "c1",
    name: "Sharma Residence",
    phone: "9800000002",
    address: "MG Road rewiring",
    createdAt: daysAgo(16),
  },
  {
    id: "cl3",
    customerId: "c2",
    name: "Green Valley Apartments",
    phone: "9800000003",
    address: "B Block fitting work",
    createdAt: daysAgo(10),
  },
];

export const seedInvoices: SeedInvoice[] = [
  {
    id: "inv1",
    invoiceNo: "INV-0001",
    type: "Wholesale",
    customerId: "c1",
    customerName: "Ramesh Kumar",
    items: [
      {
        itemId: "i5",
        name: "Copper Wire 1.5sqmm",
        qty: 100,
        price: 22,
        discount: 0,
        warrantyExpiry: null,
      },
      {
        itemId: "i8",
        name: "Switch Socket 6A",
        qty: 20,
        price: 45,
        discount: 5,
        warrantyExpiry: null,
      },
    ],
    totalAmount: 3055,
    paidAmount: 2000,
    paymentMethod: "Mixed",
    status: "Partial",
    buyingForClient: "Agarwal House",
    createdAt: daysAgo(2),
  },
  {
    id: "inv2",
    invoiceNo: "INV-0002",
    type: "Retail",
    customerId: null,
    customerName: null,
    items: [
      {
        itemId: "i1",
        name: "LED Bulb 9W",
        qty: 4,
        price: 75,
        discount: 0,
        warrantyExpiry: daysFromNow(365),
      },
    ],
    totalAmount: 300,
    paidAmount: 300,
    paymentMethod: "UPI",
    status: "Paid",
    buyingForClient: null,
    createdAt: daysAgo(1),
  },
  {
    id: "inv3",
    invoiceNo: "INV-0003",
    type: "Wholesale",
    customerId: "c2",
    customerName: "Suresh Patel",
    items: [
      {
        itemId: "i3",
        name: "Ceiling Fan 1200mm",
        qty: 3,
        price: 1800,
        discount: 0,
        warrantyExpiry: daysFromNow(730),
      },
      {
        itemId: "i7",
        name: "MCB 16A Single",
        qty: 10,
        price: 150,
        discount: 0,
        warrantyExpiry: null,
      },
    ],
    totalAmount: 6900,
    paidAmount: 0,
    paymentMethod: "Credit",
    status: "Unpaid",
    buyingForClient: "Green Valley Apartments",
    createdAt: daysAgo(4),
  },
];

export const seedPayments: SeedPayment[] = [
  {
    id: "pay1",
    customerId: "c1",
    customerName: "Ramesh Kumar",
    amount: 5000,
    method: "UPI",
    invoiceId: null,
    createdAt: daysAgo(3),
  },
  {
    id: "pay2",
    customerId: "c2",
    customerName: "Suresh Patel",
    amount: 10000,
    method: "Cash",
    invoiceId: null,
    createdAt: daysAgo(6),
  },
];
